name: tron_energy_wallet_core
description: The core library of Tron Energy Wallet
repository: https://github.com/Trenergy-wallet/tron-energy-wallet-core
issue_tracker: https://github.com/Trenergy-wallet/tron-energy-wallet-core/issues?q=is%3Aissue+is%3Aopen
version: 1.6.0
homepage: https://tr.energy/
publish_to: 'none'

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  bitcoin_base: ^7.0.0
  blockchain_utils: ^5.4.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  on_chain: ^7.1.0
  retrofit: ^4.9.1
  ton_dart: ^2.1.0
  tr_logger:
    git:
      url: https://github.com/Trenergy-wallet/tr_logger.git
      ref: v1.0.0
  tr_ton_wallet_service:
    git:
      url: https://github.com/Trenergy-wallet/tr_ton_wallet_service.git
      ref: v1.0.1
#    path: ../tr_ton_wallet_service

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0
  very_good_analysis: ^10.0.0

topics:
  - wallet
  - blockchain
  - tron
  - ton
  - bitcoin